// frontend/src/common/layouts/Main.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { base } from "./base";
  import { cn } from "tailwind-variants";

  type Props = {
    children: Snippet;
    class?: string;
  };

  const { children, class: className = "" }: Props = $props();
</script>

<div class="flex flex-col w-full h-full">
  {@render nav()}

  <div class={base({ className: cn("py-8 w-full h-full", className) })}>
    {@render children()}
  </div>
</div>

{#snippet nav()}
  <nav class="bg-slate-200 p-2">
    <img src="/fanoos.png" alt="" class="aspect-square w-12" />
  </nav>
{/snippet}

// frontend/src/common/layouts/main.tsx
import type { ReactNode } from "react"
import { cn } from "tailwind-variants"

import { base } from "./base"

type MainProps = {
  children: ReactNode
  className?: string
}

export const Main = ({ className, children }: MainProps) => (
  <div className="flex flex-col w-full h-full">
    <Nav />

    <div className={base({ className: cn("py-8 w-full h-full", className) })}>{children}</div>
  </div>
)

const Nav = () => (
  <nav className="bg-slate-200 p-2">
    <img src="/fanoos.png" alt="" className="aspect-square w-12" />
  </nav>
)
