// web/src/common/atoms/Field.vue
<script lang="ts" setup>
import { field } from './field'

const { container, label } = field()
const containerClass = container()
const labelClass = label()

type Props = {
  title: string
}

const props = defineProps<Props>()
</script>

<template>
  <div :class="containerClass">
    <p dir="auto" :class="labelClass">{{ title }}:</p>

    <slot />
  </div>
</template>

// frontend/src/common/atoms/Field.svelte
<script lang="ts">
  import type { ChildrenRequired } from "../utils";
  import { field } from "./field";

  const { container, label } = field();

  type Props = ChildrenRequired & {
    title: string;
  };

  let { title, children }: Props = $props();
</script>

<div class={container()}>
  <p dir="auto" class={label()}>
    {title}:
  </p>

  {@render children()}
</div>
