// web/src/common/atoms/Input.vue
<script lang="ts" setup>
import { computed } from 'vue'
import { input } from './input'

type Props = {
  class?: string
}

const props = defineProps<Props>()

const finalClass = computed(() => input({ className: props.class ?? '' }))
</script>

<template>
  <input dir="auto" :class="finalClass" v-bind="$attrs" />
</template>

// frontend/src/common/atoms/Input.svelte
<script lang="ts">
  import { input } from "./input";
  import type { HTMLInputAttributes } from "svelte/elements";

  type Props = HTMLInputAttributes;
  let { class: className = "", ...props }: Props = $props();
</script>

<input dir="auto" class={input({ className: className?.toString() })} {...props} />
