// frontend/src/common/atoms/Btn.svelte
<script lang="ts">
  import type { VariantProps } from "tailwind-variants";
  import { btn } from "./btn";
  import type { HTMLButtonAttributes } from "svelte/elements";

  type Props = VariantProps<typeof btn> & HTMLButtonAttributes;

  let { children, isIcon = false, class: className = "", ...rest }: Props = $props();
</script>

<button type="button" class={btn({ isIcon, className: className?.toString() })} {...rest}>
  {@render children?.()}
</button>

// web/src/common/atoms/Btn.vue
<script lang="ts" setup>
import { computed } from 'vue'
import type { VariantProps } from 'tailwind-variants'
import { btn } from './btn'

type Props = VariantProps<typeof btn> & {
  class?: string
}

const props = defineProps<Props>()

const buttonClass = computed(() =>
  btn({
    isIcon: props.isIcon,
    className: props.class ?? '',
  }),
)
</script>

<template>
  <button type="button" :class="buttonClass" v-bind="$attrs">
    <slot />
  </button>
</template>
